RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\Explorer\Enable ReFS\Disable_formatting_with_ReFS.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\Tiles\Disable Windows 10 Live Tiles permanently\Enable Windows 10 Live Tiles permanantly.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\Boot\Turn_On_Fast_Startup.bat"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 7\Info\Disable Disk Defragmenter task.txt"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\TakeOwnership\InstallTakeOwnership.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 7\TakeOwnership\Universal take Ownership.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x86\System32\uReFSv1.dll"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 7\Context Menu Adds\Add God Mode in Desktop Context Menu.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\Boot\Turn_Off_Fast_Startup.bat"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x86\System32\drivers\refsv1.sys"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 15063_x64\SysWOW64\wbem\refs.mof"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 15063_x86\System32\wbem\refs.mof"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x64\System32\wbem\refs.mof"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x64\SysWOW64\wbem\refs.mof"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x86\System32\wbem\refs.mof"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 7\Context Menu Adds\Add new CMD file.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 7\TakeOwnership\Take Ownership with icon.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\TakeOwnership\Take Ownership with icon.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 7\Context Menu Adds\Add God Mode in Top of Desktop Context Menu.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\Taskbar\Taskbar Context Menu Tweaker\64-bit (x64)\Load.bat"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 7\Disable Services and Functions\ManualApplication Information service.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 7\Context Menu Adds\Stop start aero.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 7\Disable Services and Functions\Restart Aero.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\Shell\Persistent Action Center\undo.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Add_AutorecoverMOFsReFSv1_Only.vbs"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\Security\Force unlock login even the account is already locked\Force unlock login even the account is already locked.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\Shell\Remove-Windows-Defender-To-Folder-Context-Menu.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\Explorer\Open Pictures With Windows Photo Viewer\Open Pictures With Windows Photo Viewer.cmd"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x64\SysWOW64\drivers\en-US\refsv1.sys.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x86\System32\drivers\en-US\refsv1.sys.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\Security\RunAsSmartscreen\RunAsSmartscreen.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x86\System32\drivers\refs.sys"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\ReFS_Volume_Version_Info_Command.txt"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\Network\Increase the time to show network filenames.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 7\Context Menu Adds\Add God Mode in Bottom of Desktop Context Menu.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 15063_x64\SysWOW64\drivers\cs-CZ\refs.sys.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 15063_x86\System32\drivers\cs-CZ\refs.sys.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\Taskmanager\en-US\taskmgr_w10-rs2_modern_x86.exe.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x64\SysWOW64\drivers\cs-CZ\refs.sys.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x86\System32\drivers\cs-CZ\refs.sys.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 15063_x64\SysWOW64\wbem\refsv1.mof"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 15063_x86\System32\wbem\refsv1.mof"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x64\System32\wbem\refsv1.mof"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x64\SysWOW64\wbem\refsv1.mof"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x86\System32\wbem\refsv1.mof"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\Internet Explorer\Disable Internet Explorer end of life upgrade notification update.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\Windows Update\Hide Windows Insider Program in SettingsUpdate & Security\Hide Windows Insider Program in SettingsUpdate & Security.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x86\System32\uReFS.dll"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 15063_x86\System32\uReFSv1.dll"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 15063_x86\System32\uReFS.dll"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 7\Disable Services and Functions\Disable Problem Reports and Solutions Control Panel Support Service.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Add_AutorecoverMOFsReFS_Only.vbs"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\Explorer\Enable ReFS\Enable_formatting_with_ReFS.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\OEM Page\Change OEM Page.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\Taskmanager\en-US\taskmgr_w10-rs2_classic_x86.exe.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\Context Menu\Recycle Bin\Remove Empty Recycle Bin context menu.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\Context Menu\Recycle Bin\Remove Empty Recycle Bin context menu.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Add_manually_THx_x64_x32.txt"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\Security\ASLR\aslr.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 7\Windows Updates\Disable automatic updates.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x64\SysWOW64\drivers\cs-CZ\refsv1.sys.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x86\System32\drivers\cs-CZ\refsv1.sys.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\OS independent\External Software\OneDrive\Remove OneDrive.cmd"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 7\Disable Services and Functions\Manual Computer Browser.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\Security\Check roaming owner profiles\Check roaming owner profiles.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 15063_x86\System32\drivers\refsv1.sys"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\Taskbar\Taskbar Context Menu Tweaker\64-bit (x64)\Release.bat"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\Security\SmartScreen\Disable Smartscreen hardening.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\.git\logs\refs\heads\master"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\.git\logs\refs\remotes\origin\HEAD"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 7\Disable Services and Functions\Disable Autorun for Network Drives.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\Explorer\Pin More than Three Contacts to Taskbar\Remove Pin More than Three Contacts to Taskbar.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\Security\Disable Compatibility-Manager\Disable Compatibility-Manager.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 15063_x64\SysWOW64\drivers\en-US\refsv1.sys.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 15063_x86\System32\drivers\en-US\refsv1.sys.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\LockScreen\Disable Login Screen Background Image\Disable Login Screen Background Image in Windows 10.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\Context Menu\Recycle Bin\Add Empty Recycle Bin context menu.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 15063_x64\SysWOW64\drivers\cs-CZ\refsv1.sys.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 15063_x86\System32\drivers\cs-CZ\refsv1.sys.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\Shell\Share with\Enable share settings.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\OS independent\Explorer\Network Connectivity Status Indicator (NCSI)\Network Connectivity Status Indicator (NCSI).reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\OS independent\Long Paths\Let Windows handle long Paths .reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x64\SysWOW64\drivers\en-US\refs.sys.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 16299 x86\System32\drivers\en-US\refs.sys.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 15063_x64\SysWOW64\drivers\en-US\refs.sys.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 15063_x86\System32\drivers\en-US\refs.sys.mui"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 8\My Computer\64-Bit restore folders in this PC.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\LockScreen\Disable Login Screen Background Image\Restore Login Screen Background Image in Windows 10.reg"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Add_manually_RS1_x64_x32.txt"
RI "e:\lang-regsettings\unsorted-\other\regtweaks\Win 10\ReFS\Build 15063_x86\System32\drivers\refs.sys"
